### ISSUE TITLE
Set timer in admin panel

### ISSUE THREAD

**Issue by shiffman** [shiffman/Presentation-Manager#5]
I would like to add an input field (or dropdown?) to set the amount of time for each presenter. (pre-filled in with the default number of minutes).

![Screen Shot 2020-12-05 at 11 14 12 AM](https://user-images.githubusercontent.com/191758/101248701-055b0e00-36eb-11eb-9ea5-f3b83bdb5856.png)

**Comment by ShawKai91** [comment]
I'll try this out

**Comment by shiffman** [comment]
Awesome, thank you @ShawKai91!

**Comment by ShawKai91** [comment]
if you didn't see my comment on the pull request answering your question 
> What is the significance of the variable name "TinMin"? Is there a reason the T is capitalized?
- no significance fill free to change it its used for the minutes input on the admin panel

**Comment by ShawKai91** [comment]
@shiffman did you forget to add me to Contributors?

**Comment by shiffman** [comment]
@all-contributors please add @ShawKai91 for code and ideas and for being so wonderfully helpful!! (Sory @ShawKai91 I did miss this!)
